# -*- coding: utf-8 -*-
"""Covid_Mobility.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1foOQi0UXCSYd6FSqbeq4DYeEvNCgUhgn
"""

import pandas as pd
mobility = pd.read_csv("https://storage.googleapis.com/aggie-hacks-us-covid19/Mobility_US")
case = pd.read_csv("https://storage.googleapis.com/aggie-hacks-us-covid19/Cases_US")

mobility

case